import type { AppMarketItem } from '../shared/types'

const BASE_TOOLS_CATALOG: AppMarketItem[] = [
  {
    id: 'hitl-approval-tool',
    nameZh: '人工审批节点工具',
    nameEn: 'HITL Approval Step',
    descriptionZh: '为工作流增加可配置的人工确认、通知路由与超时升级策略。',
    descriptionEn: 'Add configurable human approval, notification routing, and escalation timeouts to workflows.',
    pluginToolsZh: ['Slack', 'Teams', 'Gmail'],
    pluginToolsEn: ['Slack', 'Teams', 'Gmail'],
    toolActionsZh: [
      { id: 'APPROVAL_CREATE_REQUEST', description: '创建带截止时间、说明和审批人的人工审批请求。' },
      { id: 'APPROVAL_NOTIFY_REVIEWER', description: '通过消息或邮件通知指定审批人处理待办。' },
      { id: 'APPROVAL_RECORD_DECISION', description: '记录审批结果、批注和处理时间并回写流程上下文。' },
      { id: 'APPROVAL_ESCALATE_TIMEOUT', description: '在审批超时后自动升级到备用审批人或管理员。' },
    ],
    toolActionsEn: [
      { id: 'APPROVAL_CREATE_REQUEST', description: 'Create human approval requests with assignees, due dates, and context.' },
      { id: 'APPROVAL_NOTIFY_REVIEWER', description: 'Notify the assigned reviewer through chat or email channels.' },
      { id: 'APPROVAL_RECORD_DECISION', description: 'Persist approval decisions, comments, and handling timestamps.' },
      { id: 'APPROVAL_ESCALATE_TIMEOUT', description: 'Escalate overdue approvals to backup owners automatically.' },
    ],
    productLine: 'tools',
    templateCategory: 'hr-recruitment',
    publisher: 'Studio X',
    installs: '3.1k',
    rating: 4.8,
    iconFrom: '#ffd36a',
    iconTo: '#ff7b72',
  },
  {
    id: 'router-optimizer',
    nameZh: 'Router 分支优化器',
    nameEn: 'Router Branch Optimizer',
    descriptionZh: '基于规则与 LLM 的路由建议，帮助收敛复杂入职分支配置。',
    descriptionEn: 'Rule and LLM routing suggestions to simplify complex onboarding branch setup.',
    toolActionsZh: [
      { id: 'ROUTER_SCORE_BRANCHES', description: '按命中规则、历史效果和约束条件为各分支计算优先级。' },
      { id: 'ROUTER_RECOMMEND_PATH', description: '根据输入上下文推荐最合适的分支路径与路由理由。' },
      { id: 'ROUTER_SIMULATE_LOAD', description: '模拟不同分支配置下的流量分布与潜在拥塞点。' },
      { id: 'ROUTER_SUMMARIZE_GAPS', description: '总结当前路由规则中的冲突、缺口和可优化建议。' },
    ],
    toolActionsEn: [
      { id: 'ROUTER_SCORE_BRANCHES', description: 'Score branches using rules, constraints, and historical outcomes.' },
      { id: 'ROUTER_RECOMMEND_PATH', description: 'Recommend the best route path for the current context.' },
      { id: 'ROUTER_SIMULATE_LOAD', description: 'Simulate branch distribution and potential congestion risks.' },
      { id: 'ROUTER_SUMMARIZE_GAPS', description: 'Summarize rule conflicts, gaps, and optimization opportunities.' },
    ],
    productLine: 'tools',
    templateCategory: 'it-engineering',
    publisher: 'Flow Tools',
    installs: '540',
    rating: 4.3,
    badge: 'new',
    iconFrom: '#7ad7ff',
    iconTo: '#7c73ff',
  },
  {
    id: 'google-workspace-bridge',
    nameZh: 'Google Workspace 连接器',
    nameEn: 'Google Workspace Bridge',
    descriptionZh: '同步日历、Drive 与表单提交，用于入职材料收集与审批提醒。',
    descriptionEn: 'Sync Calendar, Drive, and Form submissions for onboarding intake and approval alerts.',
    pluginToolsZh: ['Gmail', 'Google Sheets'],
    pluginToolsEn: ['Gmail', 'Google Sheets'],
    toolActionsZh: [
      { id: 'GWS_CAPTURE_FORM_SUBMISSION', description: '接收 Google 表单提交并标准化为工作流可用字段。' },
      { id: 'GWS_SYNC_CALENDAR_EVENT', description: '创建或同步入职会议、培训安排和提醒事件。' },
      { id: 'GWS_WRITE_SHEET_ROW', description: '将表单结果、审批状态或回访记录写入 Google Sheets。' },
      { id: 'GWS_SHARE_DRIVE_ASSETS', description: '同步 Drive 文件权限并分发入职所需资料链接。' },
    ],
    toolActionsEn: [
      { id: 'GWS_CAPTURE_FORM_SUBMISSION', description: 'Capture Google Form submissions and normalize the payload.' },
      { id: 'GWS_SYNC_CALENDAR_EVENT', description: 'Create or sync onboarding meetings, training sessions, and reminders.' },
      { id: 'GWS_WRITE_SHEET_ROW', description: 'Write workflow records and statuses into Google Sheets.' },
      { id: 'GWS_SHARE_DRIVE_ASSETS', description: 'Sync Drive permissions and share onboarding materials.' },
    ],
    productLine: 'tools',
    templateCategory: 'productivity',
    publisher: 'Kyms Integrations',
    installs: '1.8k',
    rating: 4.7,
    iconFrom: '#5ea8ff',
    iconTo: '#7b61ff',
  },
  {
    id: 'notion-hr-kit',
    nameZh: 'Notion HR 套件',
    nameEn: 'Notion HR Kit',
    descriptionZh: '将候选人档案、设备清单与培训进度写入 Notion 数据库。',
    descriptionEn: 'Write candidate profiles, equipment lists, and training progress to Notion databases.',
    pluginToolsZh: ['Notion'],
    pluginToolsEn: ['Notion'],
    toolActionsZh: [
      { id: 'NOTION_CREATE_EMPLOYEE_PAGE', description: '创建员工主页并挂载入职资料、清单和说明。' },
      { id: 'NOTION_UPSERT_DATABASE_ROW', description: '将员工、设备或培训状态同步到指定数据库记录。' },
      { id: 'NOTION_APPEND_CHECKLIST', description: '为不同角色自动追加待办清单和责任人。' },
      { id: 'NOTION_SYNC_TRAINING_STATUS', description: '更新培训进度、完成时间和跟进备注。' },
    ],
    toolActionsEn: [
      { id: 'NOTION_CREATE_EMPLOYEE_PAGE', description: 'Create employee pages with onboarding docs and resources.' },
      { id: 'NOTION_UPSERT_DATABASE_ROW', description: 'Upsert employee, asset, and training records into Notion databases.' },
      { id: 'NOTION_APPEND_CHECKLIST', description: 'Append role-specific checklists and assignees automatically.' },
      { id: 'NOTION_SYNC_TRAINING_STATUS', description: 'Sync training progress, completion dates, and notes.' },
    ],
    productLine: 'tools',
    templateCategory: 'hr-recruitment',
    publisher: 'Notion Labs',
    installs: '960',
    rating: 4.6,
    badge: 'new',
    iconFrom: '#62d6a5',
    iconTo: '#3f8cff',
  },
  {
    id: 'notion-create-page',
    nameZh: 'Notion - Create Page',
    nameEn: 'Notion - Create Page',
    descriptionZh: '在 Notion 中创建新页面，并预填标题、正文结构与协作文档模板。',
    descriptionEn: 'Create a new page in Notion with prefilled title, body blocks, and collaboration-ready structure.',
    pluginToolsZh: ['Notion'],
    pluginToolsEn: ['Notion'],
    toolActionsZh: [
      { id: 'NOTION_CREATE_PAGE', description: '在指定 Notion workspace / parent 下创建页面。' },
      { id: 'NOTION_PREFILL_TEMPLATE', description: '自动写入页面标题、段落和默认模板块。' },
      { id: 'NOTION_ATTACH_METADATA', description: '写入负责人、状态、日期等基础元数据字段。' },
    ],
    toolActionsEn: [
      { id: 'NOTION_CREATE_PAGE', description: 'Create a Notion page under a selected parent workspace or page.' },
      { id: 'NOTION_PREFILL_TEMPLATE', description: 'Prefill title, body content, and reusable template blocks.' },
      { id: 'NOTION_ATTACH_METADATA', description: 'Attach owner, status, and date metadata for downstream workflows.' },
    ],
    productLine: 'tools',
    templateCategory: 'productivity',
    publisher: 'Notion Labs',
    installs: '1.4k',
    rating: 4.8,
    iconFrom: '#f3f4f6',
    iconTo: '#d1d5db',
    brandIcon: 'notion',
  },
  {
    id: 'gmail-draft-reply',
    nameZh: 'Gmail - Draft Reply',
    nameEn: 'Gmail - Draft Reply',
    descriptionZh: '根据上下文自动生成 Gmail 回复草稿，适合通知、确认与跟进邮件场景。',
    descriptionEn: 'Generate a Gmail draft reply from workflow context for notifications, confirmations, and follow-ups.',
    pluginToolsZh: ['Gmail'],
    pluginToolsEn: ['Gmail'],
    toolActionsZh: [
      { id: 'GMAIL_CREATE_DRAFT', description: '创建邮件回复草稿并带入收件人、主题与正文。' },
      { id: 'GMAIL_QUOTE_THREAD', description: '引用原始会话上下文生成更自然的回复内容。' },
      { id: 'GMAIL_ATTACH_SUMMARY', description: '将流程摘要、待办或审批结果写入邮件正文。' },
    ],
    toolActionsEn: [
      { id: 'GMAIL_CREATE_DRAFT', description: 'Create a reply draft with recipients, subject, and generated body content.' },
      { id: 'GMAIL_QUOTE_THREAD', description: 'Quote the existing email thread to keep reply context intact.' },
      { id: 'GMAIL_ATTACH_SUMMARY', description: 'Append workflow summary, next steps, or approval outcomes to the email body.' },
    ],
    productLine: 'tools',
    templateCategory: 'operations',
    publisher: 'Google Workspace',
    installs: '2.3k',
    rating: 4.7,
    iconFrom: '#fef3f2',
    iconTo: '#fde2e0',
    brandIcon: 'gmail',
  },
  {
    id: 'teams-send-message',
    nameZh: 'Teams - Send Message',
    nameEn: 'Teams - Send Message',
    descriptionZh: '向 Microsoft Teams 会话发送提醒、状态更新或协作消息。',
    descriptionEn: 'Send reminders, status updates, or coordination messages into Microsoft Teams conversations.',
    pluginToolsZh: ['Teams'],
    pluginToolsEn: ['Teams'],
    toolActionsZh: [
      { id: 'TEAMS_SEND_CHAT_MESSAGE', description: '向指定用户或群组会话发送 Teams 消息。' },
      { id: 'TEAMS_RENDER_STATUS_CARD', description: '用结构化内容渲染状态更新与下一步行动。' },
      { id: 'TEAMS_MENTION_MEMBER', description: '在消息中 @ 相关成员并附带上下文说明。' },
    ],
    toolActionsEn: [
      { id: 'TEAMS_SEND_CHAT_MESSAGE', description: 'Send a Teams message to a user, group, or channel thread.' },
      { id: 'TEAMS_RENDER_STATUS_CARD', description: 'Render structured status updates and action summaries in the message.' },
      { id: 'TEAMS_MENTION_MEMBER', description: 'Mention relevant members with the right operational context.' },
    ],
    productLine: 'tools',
    templateCategory: 'operations',
    publisher: 'Microsoft',
    installs: '1.1k',
    rating: 4.6,
    iconFrom: '#eff6ff',
    iconTo: '#dbeafe',
    brandIcon: 'teams',
  },
  {
    id: 'google-sheets-update-row',
    nameZh: 'Google Sheets - Update Row',
    nameEn: 'Google Sheets - Update Row',
    descriptionZh: '在 Google Sheets 中更新指定行，适合回写状态、结果与批量执行记录。',
    descriptionEn: 'Update a target row in Google Sheets for status sync, result writeback, and run tracking.',
    pluginToolsZh: ['Google Sheets'],
    pluginToolsEn: ['Google Sheets'],
    toolActionsZh: [
      { id: 'GSHEETS_MATCH_ROW', description: '按唯一键匹配目标行并定位需要更新的记录。' },
      { id: 'GSHEETS_UPDATE_COLUMNS', description: '批量更新多个列字段与状态值。' },
      { id: 'GSHEETS_APPEND_AUDIT_NOTE', description: '追加执行备注、时间戳和责任人信息。' },
    ],
    toolActionsEn: [
      { id: 'GSHEETS_MATCH_ROW', description: 'Match the target spreadsheet row using a unique key or identifier.' },
      { id: 'GSHEETS_UPDATE_COLUMNS', description: 'Update multiple columns in one writeback action.' },
      { id: 'GSHEETS_APPEND_AUDIT_NOTE', description: 'Append audit notes, timestamps, and operator information.' },
    ],
    productLine: 'tools',
    templateCategory: 'productivity',
    publisher: 'Google Workspace',
    installs: '1.7k',
    rating: 4.7,
    iconFrom: '#ecfdf3',
    iconTo: '#dcfce7',
    brandIcon: 'googleSheets',
  },
  {
    id: 'slack-notify-pack',
    nameZh: 'Slack 通知扩展包',
    nameEn: 'Slack Notify Pack',
    descriptionZh: '向频道或用户推送入职节点完成、阻塞与异常摘要消息。',
    descriptionEn: 'Push onboarding milestones, blockers, and error summaries to channels or users.',
    pluginToolsZh: ['Slack'],
    pluginToolsEn: ['Slack'],
    toolActionsZh: [
      { id: 'SLACK_SEND_CHANNEL_UPDATE', description: '向指定频道推送流程完成、延迟或阻塞状态更新。' },
      { id: 'SLACK_DM_ASSIGNEE', description: '向负责人私发提醒，附带上下文和操作入口。' },
      { id: 'SLACK_POST_BLOCKER_ALERT', description: '在异常发生时发送阻塞告警并标注优先级。' },
      { id: 'SLACK_SUMMARIZE_DAILY_STATUS', description: '汇总每日处理状态并生成简洁摘要消息。' },
    ],
    toolActionsEn: [
      { id: 'SLACK_SEND_CHANNEL_UPDATE', description: 'Send workflow milestone updates to a target Slack channel.' },
      { id: 'SLACK_DM_ASSIGNEE', description: 'DM responsible owners with context and next actions.' },
      { id: 'SLACK_POST_BLOCKER_ALERT', description: 'Post blocker alerts with severity and failure context.' },
      { id: 'SLACK_SUMMARIZE_DAILY_STATUS', description: 'Generate daily summary digests for onboarding operations.' },
    ],
    productLine: 'tools',
    templateCategory: 'customer-support',
    publisher: 'Kyms Integrations',
    installs: '1.2k',
    rating: 4.4,
    iconFrom: '#19c7c7',
    iconTo: '#6d6bff',
  },
  {
    id: 'webhook-dispatcher',
    nameZh: 'Webhook 分发器',
    nameEn: 'Webhook Dispatcher',
    descriptionZh: '将工作流事件转发至外部系统，支持重试与签名验证。',
    descriptionEn: 'Forward workflow events to external systems with retries and signature verification.',
    pluginToolsZh: ['Slack', 'Teams'],
    pluginToolsEn: ['Slack', 'Teams'],
    toolActionsZh: [
      { id: 'WEBHOOK_FORWARD_EVENT', description: '将指定工作流事件转发到外部 HTTP 端点。' },
      { id: 'WEBHOOK_SIGN_PAYLOAD', description: '对请求体进行签名，便于外部系统校验来源。' },
      { id: 'WEBHOOK_RETRY_DELIVERY', description: '在失败时按策略自动重试并记录重放结果。' },
      { id: 'WEBHOOK_RECORD_RESPONSE', description: '保存响应码、耗时和异常信息用于排查。' },
    ],
    toolActionsEn: [
      { id: 'WEBHOOK_FORWARD_EVENT', description: 'Forward workflow events to external HTTP endpoints.' },
      { id: 'WEBHOOK_SIGN_PAYLOAD', description: 'Sign outbound payloads for source verification.' },
      { id: 'WEBHOOK_RETRY_DELIVERY', description: 'Retry failed deliveries based on configured policies.' },
      { id: 'WEBHOOK_RECORD_RESPONSE', description: 'Record response codes, latency, and failure details.' },
    ],
    productLine: 'tools',
    templateCategory: 'it-engineering',
    publisher: 'Flow Tools',
    installs: '740',
    rating: 4.5,
    iconFrom: '#7f7cff',
    iconTo: '#ff9a62',
  },
  {
    id: 'form-field-validator',
    nameZh: '表单字段校验器',
    nameEn: 'Form Field Validator',
    descriptionZh: '对入职表单输入做格式、必填与跨字段规则校验。',
    descriptionEn: 'Validate onboarding form inputs with format, required, and cross-field rules.',
    pluginToolsZh: ['Google Sheets'],
    pluginToolsEn: ['Google Sheets'],
    toolActionsZh: [
      { id: 'FORM_VALIDATE_REQUIRED_FIELDS', description: '校验必填字段是否完整并输出缺失项列表。' },
      { id: 'FORM_CHECK_REGEX_RULES', description: '根据格式规则检查邮箱、手机号和编号字段。' },
      { id: 'FORM_COMPARE_CROSS_FIELDS', description: '执行跨字段一致性与依赖关系校验。' },
      { id: 'FORM_RETURN_ERROR_SUMMARY', description: '返回可读的错误摘要，供前端或 Agent 提示用户。' },
    ],
    toolActionsEn: [
      { id: 'FORM_VALIDATE_REQUIRED_FIELDS', description: 'Validate required fields and report missing inputs.' },
      { id: 'FORM_CHECK_REGEX_RULES', description: 'Check email, phone, and ID fields against format rules.' },
      { id: 'FORM_COMPARE_CROSS_FIELDS', description: 'Run cross-field dependency and consistency checks.' },
      { id: 'FORM_RETURN_ERROR_SUMMARY', description: 'Return human-readable validation summaries for UI or agent prompts.' },
    ],
    productLine: 'tools',
    templateCategory: 'operations',
    publisher: 'Studio X',
    installs: '620',
    rating: 4.4,
    iconFrom: '#ff8cb7',
    iconTo: '#9a6bff',
  },
  {
    id: 'schedule-trigger-tool',
    nameZh: '定时触发工具',
    nameEn: 'Schedule Trigger Tool',
    descriptionZh: '按 cron 或工作日历触发工作流，适用于回访与提醒场景。',
    descriptionEn: 'Trigger workflows on cron or business calendars for check-ins and reminders.',
    pluginToolsZh: ['Gmail', 'Teams'],
    pluginToolsEn: ['Gmail', 'Teams'],
    toolActionsZh: [
      { id: 'SCHEDULE_RUN_CRON_JOB', description: '按 cron 规则触发固定任务或工作流执行。' },
      { id: 'SCHEDULE_SKIP_HOLIDAYS', description: '结合工作日历自动跳过节假日和非工作时间。' },
      { id: 'SCHEDULE_SEND_REMINDER', description: '在关键时间节点发送回访或待办提醒。' },
      { id: 'SCHEDULE_RESCHEDULE_MISSED_RUN', description: '对错过的执行窗口进行补跑或重新排期。' },
    ],
    toolActionsEn: [
      { id: 'SCHEDULE_RUN_CRON_JOB', description: 'Trigger workflows on cron-based schedules.' },
      { id: 'SCHEDULE_SKIP_HOLIDAYS', description: 'Skip runs on holidays and outside business calendars.' },
      { id: 'SCHEDULE_SEND_REMINDER', description: 'Send reminders at important onboarding checkpoints.' },
      { id: 'SCHEDULE_RESCHEDULE_MISSED_RUN', description: 'Replay or reschedule missed execution windows.' },
    ],
    productLine: 'tools',
    templateCategory: 'operations',
    publisher: 'Kyms Integrations',
    installs: '880',
    rating: 4.6,
    badge: 'featured',
    iconFrom: '#ffb86c',
    iconTo: '#ff6ea8',
  },
]

const PROMOTED_TOOL_IDS = [
  'notion-create-page',
  'gmail-draft-reply',
  'teams-send-message',
  'google-sheets-update-row',
] as const

export const TOOLS_CATALOG: AppMarketItem[] = [
  ...PROMOTED_TOOL_IDS.flatMap((id) => BASE_TOOLS_CATALOG.filter((item) => item.id === id)),
  ...BASE_TOOLS_CATALOG.filter((item) => !PROMOTED_TOOL_IDS.includes(item.id as (typeof PROMOTED_TOOL_IDS)[number])),
]

export function findToolById(id: string): AppMarketItem | undefined {
  return TOOLS_CATALOG.find((item) => item.id === id)
}
