import type { AppMarketItem } from '../shared/types'

export const SKILLS_CATALOG: AppMarketItem[] = [
  {
    id: 'onboarding-guide-skill',
    nameZh: '入职办理引导技能',
    nameEn: 'Onboarding Guide Skill',
    descriptionZh: '引导新员工完成材料提交、表单填写与关键节点确认，统一话术与补交指引。',
    descriptionEn:
      'Guide new hires through document submission, forms, and key checkpoints with consistent prompts and resubmission help.',
    modalDescriptionZh:
      '面向员工自助入职场景，提供分步引导、缺件清单与截止时间说明，可与资料提交子代理协同使用。',
    modalDescriptionEn:
      'Step-by-step self-onboarding guidance with missing-item lists and deadlines; pairs with document submission sub-agents.',
    productLine: 'skills',
    templateCategory: 'hr-recruitment',
    publisher: 'Studio X',
    installs: '2.4k',
    rating: 4.9,
    badge: 'featured',
    iconFrom: '#a78bfa',
    iconTo: '#6366f1',
    pluginToolsZh: ['Google Drive', 'Gmail'],
    pluginToolsEn: ['Google Drive', 'Gmail'],
  },
  {
    id: 'notification-tracking-skill',
    nameZh: '通知与状态跟踪技能',
    nameEn: 'Notification Tracking Skill',
    descriptionZh: '汇总流程节点状态，发送提醒并在超时未闭环时升级通知责任人。',
    descriptionEn:
      'Aggregate workflow status, send reminders, and escalate when critical steps remain open past SLA.',
    productLine: 'skills',
    templateCategory: 'operations',
    publisher: 'Studio X',
    installs: '1.8k',
    rating: 4.7,
    iconFrom: '#38bdf8',
    iconTo: '#0ea5e9',
    pluginToolsZh: ['Slack', 'Gmail'],
    pluginToolsEn: ['Slack', 'Gmail'],
  },
  {
    id: 'hr-provisioning-skill',
    nameZh: 'HR 开通协调技能',
    nameEn: 'HR Provisioning Skill',
    descriptionZh: '协调 IT 开通、权限申请与设备确认，输出员工可读的状态摘要与排障建议。',
    descriptionEn:
      'Coordinate IT provisioning, access requests, and device checks with employee-friendly status summaries.',
    productLine: 'skills',
    templateCategory: 'it-engineering',
    publisher: 'Kyms Integrations',
    installs: '960',
    rating: 4.6,
    badge: 'new',
    iconFrom: '#34d399',
    iconTo: '#059669',
    pluginToolsZh: ['Slack', 'Microsoft Teams'],
    pluginToolsEn: ['Slack', 'Microsoft Teams'],
  },
  {
    id: 'document-checklist-skill',
    nameZh: '材料核对与缺件追踪技能',
    nameEn: 'Document Checklist Skill',
    descriptionZh: '按岗位与地区规则核对入职材料，生成可点击补交清单并指派责任人。',
    descriptionEn:
      'Verify onboarding documents by role and region; produce actionable missing-item lists with owners.',
    productLine: 'skills',
    templateCategory: 'hr-recruitment',
    publisher: 'Studio X',
    installs: '1.2k',
    rating: 4.8,
    iconFrom: '#fbbf24',
    iconTo: '#f97316',
    pluginToolsZh: ['Google Drive', 'Notion'],
    pluginToolsEn: ['Google Drive', 'Notion'],
  },
  {
    id: 'approval-routing-skill',
    nameZh: '审批路由摘要技能',
    nameEn: 'Approval Routing Summary Skill',
    descriptionZh: '为人工审批节点生成上下文摘要、建议路由与升级路径，减少审批人阅读成本。',
    descriptionEn:
      'Summarize context and suggest approval routes and escalations for human-in-the-loop steps.',
    productLine: 'skills',
    templateCategory: 'operations',
    publisher: 'Flow Tools',
    installs: '720',
    rating: 4.5,
    iconFrom: '#f472b6',
    iconTo: '#ec4899',
    pluginToolsZh: ['Gmail', 'Slack'],
    pluginToolsEn: ['Gmail', 'Slack'],
  },
  {
    id: 'training-checkin-skill',
    nameZh: '培训签到催办技能',
    nameEn: 'Training Check-in Nudge Skill',
    descriptionZh: '安排培训日程、发送签到提醒并跟进未完成课程，输出缺席原因汇总。',
    descriptionEn:
      'Schedule training, send check-in reminders, and follow up on incomplete courses with absence summaries.',
    productLine: 'skills',
    templateCategory: 'hr-recruitment',
    publisher: 'Studio X',
    installs: '640',
    rating: 4.4,
    iconFrom: '#c084fc',
    iconTo: '#8b5cf6',
    pluginToolsZh: ['Slack', 'Google Calendar'],
    pluginToolsEn: ['Slack', 'Google Calendar'],
  },
  {
    id: 'crm-handoff-skill',
    nameZh: 'CRM 线索交接技能',
    nameEn: 'CRM Handoff Skill',
    descriptionZh: '整理销售线索上下文、下一步动作与风险提示，便于经理快速接手跟进。',
    descriptionEn:
      'Package sales lead context, next actions, and risks for fast manager handoff in CRM workflows.',
    productLine: 'skills',
    templateCategory: 'business-dev',
    publisher: 'Revenue Ops Lab',
    installs: '510',
    rating: 4.3,
    iconFrom: '#60a5fa',
    iconTo: '#2563eb',
    pluginToolsZh: ['CRM MCP', 'Gmail'],
    pluginToolsEn: ['CRM MCP', 'Gmail'],
  },
  {
    id: 'web-research-skill',
    nameZh: '网页搜索调研技能',
    nameEn: 'Web Research Skill',
    descriptionZh: '为内容选题与竞品分析抓取公开信息，输出带来源链接的结构化要点。',
    descriptionEn:
      'Gather public web signals for content ideation and competitor scans with sourced bullet summaries.',
    productLine: 'skills',
    templateCategory: 'marketing',
    publisher: 'Growth Kit',
    installs: '890',
    rating: 4.6,
    iconFrom: '#2dd4bf',
    iconTo: '#14b8a6',
    pluginToolsZh: ['网页搜索', 'Notion'],
    pluginToolsEn: ['Web Search', 'Notion'],
  },
]

export function findSkillById(id: string): AppMarketItem | undefined {
  return SKILLS_CATALOG.find((item) => item.id === id)
}
